spring:
  security:
    user:
      name: admin
      password: admin
  ##  database info
  datasource:
     url: jdbc:postgresql://localhost:5432/modeluser?createDatabaseIfNotExist=true
     username: postgres
     password: dancali
     driver-class-name: org.postgresql.Driver
    #render connexion reussi
#   url: jdbc:postgresql://dpg-cl4gdsiuuipc73a8dal0-a.oregon-postgres.render.com:5432/muslembd
#   username: muslembd_user
#   password: 6TNb3FBLLsVq2adCAZAAuVItWE1Pc1Uu
#   driver-class-name: org.postgresql.Driver
    #connexion a neon Test toujours encours
#         url: jdbc:postgresql://ep-solitary-wind-02190521-pooler.us-east-2.aws.neon.tech/muslembd?sslmode=require
#         username: ibrahimsandah12
#         password: 7MYyUVThqta8
#         driver-class-name: org.postgresql.Driver
        #  gestion des session jdbc
#  session:
#    jdbc:
#      initialize-schema: always
      ## Gmail configuration for sending email
  mail:
    host: smtp.gmail.com
    port: 587
    protoco: smtps
    username: ibrahimsandah12@gmail.com
    password: lpfk mqjd gmoo yrma
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
    ## End
  jpa:
    ##show-sql: true
    ##  Hibernate DDL create, update...
    hibernate:
      ddl-auto: update
    ## Generation du schemat de la base de donnee;
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ## setting time zone
#        jdbc:
#          time_zone: UTC+1
        ## configuration de envers
        org:
          hibernate:
            envers:
              default_schema: m_app_audit
    ## to allow circular and override bean definition
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    ## multipart file configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20MB
      max-file-size: 20MB
      max-request-size: 30MB
    ## end
    ## allow OPTIONS request
#  mvc:
#  dispatch-options-request: true
#    actuator
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: health,info
#    end
server:
  port: 8080
  # erreur : desactivé page blanche
#  error:
#    whitelabel:
#      enabled: false
# application information
#file stage location
file:
  storage:
    location: fileStorageDir
  ## File path config
project:
  poster: fileStorage/
#end
application:
  title: muslimApp
  version: 1.0