package com.theh.moduleuser.Exceptions;

public enum ErrorCodes {

	GENERAL_ENTITY_NOT_FOUND(011),
	LOCALISATION_NOT_FOUND(100),
	LOCALISATION_NOT_VALID(101),
	MOSQUE_NOT_FOUND(200),
	MOSQUE_NOT_VALID(201),
	MOSQUE_NOT_EXIST(202),
	IMAM_NOT_FOUND(300),
	IMAM_NOT_VALID(301),
	IMAM_NOT_EXIST(302),
	SERMONT_NOT_FOUND(400),
	SERMONT_NOT_VALID(401),
	SERMONT_NOT_EXIST(402),
	PREDICATION_NOT_VALID(500),
	PREDICATION_NOT_FOUND(501),
	PREDICATION_NOT_EXIST(502),
	UTILISATEUR_NOT_VALID(600),
	UTILISATEUR_NOT_FOUND(601),
	UTILISATEUR_NOT_EXIST(602),
	UTILISATEUR_PASSWD_INCORECT(603),
	UTILISATEUR_ALREADY_EXIST(603),
	SIMPLE_UTILISATEUR(604),
	ROLE_NOT_VALID(700),
	ROLE_NOT_FOUND(701),
	ROLE_NOT_EXIST(702),
	DOCUMENTS_NOT_FOUND(800),
	DOCUMENTS_NOT_VALID(801),
	DOCUMENTS_NOT_EXIST(802),
	UNKNOW_CONTEXT(900),
	BAD_CREDENTIAL(1000),
	SUIVRE_NOT_VALID(2000),
	NOTIFICATION_NOT_VALID(3000),
	FILE_NOT_FOUND(4000),
	UNAUTHORIZE(5000)
	;
	private int code;
	ErrorCodes(int code){
		this.code=code;
	}
	public int getCode() {
		return code;
	}
}
